### ISSUE TITLE
[BUG] ModuleNotFoundError for ipython_genutils

### ISSUE THREAD

**Issue by AlpAribal** [s-weigand/flake8-nb#206] opened 2022-03-11 11:51 UTC
**Describe the bug**
After the recent ipython version bump, our flake8-nb precommit hooks started failing with the error: `ModuleNotFoundError: No module named 'ipython_genutils'`.

**To Reproduce**

```
conda create -n test python=3.8
conda activate test
pip install flake8-nb
python
>>> import flake8_nb
```

**Expected behavior**
`flake8_nb` should be imported without any errors.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version 20.04

**Additional context**
This might be due to ipykernel not stating its dependencies properly, see [here](https://github.com/ipython/ipykernel/issues/759).

**Comment by s-weigand** [comment] 2022-03-11 12:37
Thanks for reporting this error!
I can reproduce it. 
It seems to be an [issue with nbconvert](https://github.com/jupyter/nbconvert/issues/1725) which uses `ipython_genutils` directly without declaring it in their dependencies, but a [hotfix is already on its way](https://github.com/jupyter/nbconvert/pull/1726).
This bug is atm [only 16h old](https://github.com/jupyter/nbformat/releases/tag/5.2.0) and most likely won't get 24h old, so I would say just wait a bit.
Having indirect dependencies which piggybacked in with a dependency of a dependency is a quite common problem with python packages, so huge props for the `nbconvert` maintainers for their quick reaction.

If you urgently need to keep on working you can just add `ipython_genutils` as an additional dependency as a quick fix in your `.pre-commit-config.yaml`

```yaml
- repo: https://github.com/s-weigand/flake8-nb
  rev: 0.4.0
  hooks:
  - id: flake8-nb
    additional_dependencies: [ipython_genutils]
```

Since this is an upstream problem that will soon be fixed I will close the issue.

**Closed by s-weigand** 2022-03-11 12:37 UTC
Labels: bug

**Comment by s-weigand** [comment] 2022-03-11 12:38
@all-contributors please add @AlpAribal  for bug

**Comment by s-weigand** [comment] 2022-03-11 17:33
@AlpAribal `nbconvert` made a [new release](https://pyglotaran--1015.org.readthedocs.build/en/1015/api/glotaran/utils/io/glotaran.utils.io.extract_sas.html#glotaran.utils.io.extract_sas) and the issue is fixed (see [update PR with passing CI](https://github.com/s-weigand/flake8-nb/pull/208)).
If `pre-commit` uses the cached version of the broken env you can just do a `pre-commit clean` to remove all cached envs.

**Comment by AlpAribal** [comment] 2022-03-11 17:33
Thank you for the update, that was fast!
